### PR TITLE
Support for resource maps

### PR DESCRIPTION
**Pull request by dretay**
Hey David, 

We're using just copy to solve a problem staging some css resources from the ace editor. Ace wants to fetch its own stylesheets and expects them to be co-located with the javascript. 

I modified the just-copy plugin to support this use case by allowing you to specify both a source and a destination, rather than just a source. 

You can add it to your config with something like the following: 

```
  justCopy:
    paths:[
      {
        src: "stylesheets/vendor/ace"
        dest: "javascripts/vendor/ace"
      }
    ]
```

### CODE REVIEW

**Comment by dbashford** [comment]
Just peeking at your example there, not yet at code.  Can one mix and match objects with `src`/`dest` with string paths, or is it one or the other?

**Comment by dretay** [comment]
I didn't test it but yes, you should be able to mix and match.

**Comment by dbashford** [comment]
Cool!  So, conceptually, I good with the feature.  I should be able to find the time before COB tomorrow to pull this in and give it a run through before publishing.

Good stuff! Thanks!

**Comment by dbashford** [comment]
Published as `0.3.0`.  Great feature!  Thanks!!

**Pull request merged**
